name: Code Check and Build flow
on:
  workflow_call:

jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
      - name: Display Node version
        run: |
          node --version
          npm --version
      - name: Install dependencies
        run: npm ci
      - name: Run format checks
        run: npm run fmt-check
      - name: Run lint
        run: npm run lint 
      # - name: Build code
      #   run: npm run build
