name: Vercel Deployments
on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: The environment to deploy to.
        required: true
        default: 'production'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: "${{ inputs.environment == 'production' && '--prod' || '--target=staging' }}"
      - run: echo "Deploying to ${{ inputs.environment }} environment"
